server:
  port: 8080

spring:
  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:mem:nutricao
    username: sa
    password: password
    driverClassName: org.h2.Driver
    initialization-mode: never

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: update
    show-sql: true